config/routes.rb
Poetrybin::Application.routes.draw do
  resources :poems do
    member do
      put 'hide'
    end
  end
  get 'random', to: 'poems#random'
  get 'about', to: 'pages#about'
  resource :session, only: [:new, :create, :destroy]
  root to: 'poems#random'
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  validates :body, uniqueness: true, presence: true
  scope :visible, -> {where(hidden: false)}
  scope :newest_first, -> {order('created_at DESC')}

  def self.random
    order('RANDOM()').first
  end

  def display_title
    return title if !title.blank?
    display_title = Formatter.strip_carriage_returns(body).scan(/^(.+?)$/).flatten.first
    if display_title.scan(/[\w-]+/).size > 5
      display_title = "#{body.split(' ')[0...5].join(' ')}…"
    end
    display_title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?

  private

  def logged_in?
    session[:admin]
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def login
  end

  def check_password
    if params[:password] == ENV['PASSWORD']
      session[:admin] = true
    end
    redirect_to poems_path
  end

  def logout
    session.destroy
    redirect_to poems_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  def index
    @poems = Poem.visible.newest_first
  end

  def show
    @poem = Poem.find(params[:id])
  end

  def random
    @poem = Poem.visible.random
    render :show
  end

  def new
    @poem = Poem.new
  end

  def create
    @poem = Poem.create(params.require(:poem).permit(:title, :body))
    redirect_to poem_path(@poem)
  end

  def hide
    if logged_in?
      @poem = Poem.find(params[:id])
      @poem.update_attribute(:hidden, true)
    end
    redirect_to poems_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if params[:password] == ADMIN_PASSWORD
      session[:admin] = true
    end
    redirect_to poems_path
  end

  def destroy
    session.destroy
    redirect_to poems_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poetrybin</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<nav>
  <ul>
    <li><%= link_to 'See all poems', poems_path %></li>
    <li><%= link_to 'Random', random_path %></li>
    <li><%= link_to 'Add a poem', new_poem_path %></li>
    <% if logged_in? %>
      <li><%= button_to 'Logout', session_path, method: :delete %></li>
    <% end %>
  </ul>
</nav>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Poetrybin
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Inconsolata:400,700'
    = stylesheet_link_tag :application
    = csrf_meta_tag

    %meta{ name: 'description', content: 'Poetrybin is a place where you can post poems anonymously' }/
    %meta{ name: 'keywords', content: 'poetrybin, poetry, poem, anonymous' }/
    %meta{ name: 'author', content: '@ntlk, http://twitter.com/ntlk' }/


  %body

    .main
      .content
        = yield
      .sidebar
        %header= link_to image_tag('poetrybin.png'), root_path
        %nav
          %ul
            %li= link_to 'Add a poem', new_poem_path
            %li= link_to 'Random', random_path
            %li= link_to 'See all poems', poems_path
            - if logged_in?
              %li= button_to 'Logout', session_path, method: :delete
            %li.what= link_to 'What is this?', about_path

app/views/pages/about.html.haml
.poem
  %p Poetrybin is a project inspired by <a href="http://ntlk.net/images/6412166473_b1a80262ce_o.png">this tweet</a>. You can only post poems anonymously, and you can't edit or delete them.
  %p Made by <a href="http://twitter.com/ntlk">ntlk</a>.

app/views/poems/index.html.haml
- @poems.each do |poem|
  .poem-list__item
    %time.poem-list__date= poem.created_at
    .poem-list__link= link_to poem.display_title, poem_path(poem)
    - if logged_in?
      = button_to 'Hide', hide_poem_path(poem), method: :put

app/views/poems/new.html.haml
= form_for @poem do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body, 'Poem'
  = f.text_area :body
  = f.submit 'Save'


.markdown-info
  You can use basic formatting in your poems. Pressing return will be interpreted as new line. Asterisks provide <em>*emphasis*</em> and <strong>**boldening**</strong>.
  %br
  %br To vary the size of text use hashes at the beginning of the line, like so:
  %br
  %h1 # One for biggest text
  %h2 ## Two for slightly smaller
  %h3 ### Three...
  %h4 #### And four
  %br ...and the smallest size is the regular text.

app/views/poems/show.html.haml
- if @poem
  .poem
    .poem__title= @poem.title
    .poem__body= Formatter.format(@poem.body)
    = @poem.created_at